#!/usr/bin/env python3
"""Refresh the local Free in NYC website from the collector's output.

Usage (from this folder):
    python update_site.py                       # reads ../fr33_collector/out/events.json
    python update_site.py path/to/events.json   # or any collect.py output

Writes public/events.js next to public/index.html. Open public/index.html in a browser to view the site.
Run the collector first to get fresh events:
    cd ../fr33_collector && python collect.py --days 31
"""
import json, os, sys
from datetime import date, datetime, timedelta, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from build_db import to_event  # same cleaning, borough and category rules as the hosted site


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "fr33_collector", "out", "events.json")
    with open(src, encoding="utf-8") as f:
        data = json.load(f)
    today = date.today()
    end = today + timedelta(days=31)
    if data.get("window"):
        end = max(end, date.fromisoformat(data["window"][1]))
    events, seen = [], set()
    for raw in data.get("events", []):
        ev = to_event(raw)
        if not ev or ev["id"] in seen:
            continue
        if not (today <= date.fromisoformat(ev["date"]) <= end):
            continue
        seen.add(ev["id"])
        events.append(ev)
    events.sort(key=lambda e: (e["date"], e["start_time"] or "", e["title"]))
    payload = {
        "updated_at": data.get("generated_at") or datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "built_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "event_count": len(events),
        "events": events,
    }
    out = os.path.join(HERE, "public", "events.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("/* Generated by update_site.py. Do not edit by hand. */\n")
        f.write("window.FREE_EVENTS_DATA = ")
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print(f"{len(events)} free events written to {out}")


if __name__ == "__main__":
    main()
